# Тема “Вычисления с помощью Numpy”

### Задание 1

Импортируйте библиотеку Numpy и дайте ей псевдоним np.

Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [1]:
import numpy as np

a = np.array([
    [1, 2, 3, 3, 1],
    [6, 8, 11, 10, 7]
]).T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [2]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

### Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [3]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [4]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
a_centered_sp

8.0

In [5]:
a_cov = a_centered_sp / ( a.shape[0] - 1 )
a_cov

2.0

### Задание 4**

Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.

Подробнее узнать о ковариации можно здесь:

[Выборочная ковариация и выборочная дисперсия — Студопедия](https://studopedia.ru/9_153900_viborochnaya-kovariatsiya-i-viborochnaya-dispersiya.html)

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.


In [6]:
a_np_cov = np.cov(a.T)[0,1]
a_np_cov

2.0

# Тема “Работа с данными в Pandas”

### Задание 1

Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].

Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  

[1, 1, 1, 2, 2, 3, 3],

['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],

[450, 300, 350, 500, 450, 370, 290].

In [7]:
import pandas as pd

authors = pd.DataFrame(
    {
        'author_id': [1, 2, 3], 
        'author_name': ['Тургенев', 'Чехов', 'Островский']
    }
)

authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [8]:
book = pd.DataFrame(
    {
        'author_id': [1, 1, 1, 2, 2, 3, 3],
        'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
        'price': [450, 300, 350, 500, 450, 370, 290]
    }
)
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### Задание 2

Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [9]:

authors_price = pd.merge(authors, book, on = 'author_id', how = 'outer')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Задание 3

Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [10]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [11]:
top5 = authors_price.sort_values(by='price', inplace=False)[::-1][:5]
top5.reset_index(drop=True, inplace=True)
top5

author_id author_name         book_title  price
0          2       Чехов   Толстый и тонкий    500
1          2       Чехов    Дама с собачкой    450
2          1    Тургенев        Отцы и дети    450
3          3  Островский              Гроза    370
4          1    Тургенев  Дворянское гнездо    350

In [12]:
top5 = authors_price.sort_values(by=['price'], ascending=False).iloc[:5, :]
top5.reset_index(drop=True, inplace=True)
top5

author_id author_name         book_title  price
0          2       Чехов   Толстый и тонкий    500
1          1    Тургенев        Отцы и дети    450
2          2       Чехов    Дама с собачкой    450
3          3  Островский              Гроза    370
4          1    Тургенев  Дворянское гнездо    350

### Задание 4

Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:

author_name, min_price, max_price и mean_price,

в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.

In [13]:
# Variant 1
gb = authors_price.groupby('author_name')
authors_stat = pd.DataFrame(
    {
        'min_price': gb['price'].min(),
        'max_price': gb['price'].max(),
        'mean_price': gb['price'].mean(),
    }
)

authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000

In [14]:
# Var 2
authors_stat = authors_price.groupby('author_name').agg(
    min_price=('price', 'min'),
    max_price=('price', 'max'),
    mean_price=('price', 'mean')
)
authors_stat.reset_index(inplace=True)
authors_stat

author_name  min_price  max_price  mean_price
0  Островский        290        370  330.000000
1    Тургенев        300        450  366.666667
2       Чехов        450        500  475.000000

In [15]:
# Var 3
authors_stat = authors_price.groupby('author_name').agg({'price': ['min', 'max', 'mean']})
authors_stat = authors_stat.rename(
    columns = {'min':'min_price', 'max':'max_price', 'mean':'mean_price'}
)
authors_stat.reset_index(inplace=True)
authors_stat

author_name     price                      
              min_price max_price  mean_price
0  Островский       290       370  330.000000
1    Тургенев       300       450  366.666667
2       Чехов       450       500  475.000000

In [16]:
# Var 4
authors_stat = authors_price.groupby('author_name').agg({'price': ['min', 'max', 'mean']})
authors_stat.columns = ['min_price', 'max_price', 'mean_price']
authors_stat.reset_index(inplace=True)
authors_stat

author_name  min_price  max_price  mean_price
0  Островский        290        370  330.000000
1    Тургенев        300        450  366.666667
2       Чехов        450        500  475.000000

In [17]:
# Var 5
authors_stat = authors_price.groupby('author_name').agg(
    {
        'price': [
            ('min_price', 'min'), 
            ('max_price', 'max'), 
            ('mean_price', 'mean')
        ]
    }
)
authors_stat.reset_index(inplace=True)
authors_stat

author_name     price                      
              min_price max_price  mean_price
0  Островский       290       370  330.000000
1    Тургенев       300       450  366.666667
2       Чехов       450       500  475.000000

In [18]:
# Var 6
grouped_by_name = authors_price.groupby('author_name')
authors_stat_v1 = grouped_by_name.describe().iloc[:, [9, 11, 15]]
authors_stat

author_name     price                      
              min_price max_price  mean_price
0  Островский       290       370  330.000000
1    Тургенев       300       450  366.666667
2       Чехов       450       500  475.000000

In [19]:
authors_stat_v2 = grouped_by_name.describe()['price'][['mean', 'min', 'max']]
authors_stat

author_name     price                      
              min_price max_price  mean_price
0  Островский       290       370  330.000000
1    Тургенев       300       450  366.666667
2       Чехов       450       500  475.000000

In [20]:
?pd.DataFrame.describe

Signature:
pd.DataFrame.describe(
    self: 'FrameOrSeries',
    percentiles=None,
    include=None,
    exclude=None,
    datetime_is_numeric=False,
) -> 'FrameOrSeries'
Docstring:
Generate descriptive statistics.

Descriptive statistics include those that summarize the central
tendency, dispersion and shape of a
dataset's distribution, excluding ``NaN`` values.

Analyzes both numeric and object series, as well
as ``DataFrame`` column sets of mixed data types. The output
will vary depending on what is provided. Refer to the notes
below for more detail.

Parameters
----------
percentiles : list-like of numbers, optional
    The percentiles to include in the output. All should
    fall between 0 and 1. The default is
    ``[.25, .5, .75]``, which returns the 25th, 50th, and
    75th percentiles.
include : 'all', list-like of dtypes or None (default), optional
    A white list of data types to include in the result. Ignored
    for ``Series``. Here are the options:

    - 'all' : All col

### Задание 5**

Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:

['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].

Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.

Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

In [21]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [22]:
?pd.pivot_table

Signature:
pd.pivot_table(
    data: 'DataFrame',
    values=None,
    index=None,
    columns=None,
    aggfunc: 'AggFuncType' = 'mean',
    fill_value=None,
    margins=False,
    dropna=True,
    margins_name='All',
    observed=False,
    sort=True,
) -> 'DataFrame'
Docstring:
Create a spreadsheet-style pivot table as a DataFrame.

The levels in the pivot table will be stored in MultiIndex objects
(hierarchical indexes) on the index and columns of the result DataFrame.

Parameters
----------
data : DataFrame
values : column to aggregate, optional
index : column, Grouper, array, or list of the previous
    If an array is passed, it must be the same length as the data. The
    list can contain any of the other types (except list).
    Keys to group by on the pivot table index.  If an array is passed,
    it is being used as the same manner as column values.
columns : column, Grouper, array, or list of the previous
    If an array is passed, it must be the same length as the data. The

In [23]:
#Variant 1
book_info = pd.pivot_table(
    data=authors_price, 
    values='price', 
    index=['author_name'], 
    columns=['cover'], 
    aggfunc=np.sum
)
book_info['мягкая'] = book_info['мягкая'].fillna(0)
book_info['твердая'] = book_info['твердая'].fillna(0)
book_info

cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0

In [24]:
#Variant 2
book_info = pd.pivot_table(
    data=authors_price, 
    values='price',
    index='author_name',
    columns='cover',
    aggfunc='sum',
    fill_value=0,
    dropna=False
)
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [25]:
book_info.to_pickle('book_info.pkl')

In [26]:
book_info2 = pd.read_pickle('book_info.pkl')

In [27]:
book_info.equals(book_info2)

True

In [28]:
book_info == book_info2

cover        мягкая  твердая
author_name                 
Островский     True     True
Тургенев       True     True
Чехов          True     True

In [29]:
book_info.compare(book_info2, keep_shape=True, keep_equal=True)

cover       мягкая       твердая      
              self other    self other
author_name                           
Островский     660   660       0     0
Тургенев       650   650     450   450
Чехов            0     0     950   950